-- MCQ Results Table for Privacy-Focused Sync
-- This table stores anonymous test results with hashed IDs

CREATE TABLE IF NOT EXISTS mcq_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_id TEXT NOT NULL,
  score INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percentage INTEGER NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  synced BOOLEAN DEFAULT true
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_mcq_results_anonymous_id ON mcq_results(anonymous_id);
CREATE INDEX IF NOT EXISTS idx_mcq_results_timestamp ON mcq_results(timestamp DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE mcq_results ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read for admin (you can add your own policy)
CREATE POLICY "Allow read for authenticated users" 
ON mcq_results FOR SELECT 
TO authenticated, anon 
USING (true);

-- Allow anonymous insert
CREATE POLICY "Allow anonymous insert" 
ON mcq_results FOR INSERT 
TO authenticated, anon 
WITH CHECK (true);

-- Allow anonymous delete (for privacy - users can delete their own data)
CREATE POLICY "Allow anonymous delete" 
ON mcq_results FOR DELETE 
TO authenticated, anon 
USING (true);
